### ISSUE TITLE
Streaming restarts at zero, after a couple of minutes

### ISSUE THREAD

**Issue by pannal** [enen92/script.tubecast#3] opened 2018-05-16 17:15 UTC
Please find the original issue here: https://github.com/jdf76/plugin.video.youtube/issues/340#issuecomment-389595761

It seems like it's caused by script.tubecast and not plugin.video.youtube.

**Comment by rcojr** [comment] 2018-05-16 20:52
I have the same problem here.. The add-on is very good except for this annoying problem

**Comment by enen92** [comment] 2018-05-16 21:44
Steps to reproduce?

**Comment by pannal** [comment] 2018-05-16 22:03
- use the youtube app to cast to OSMC/TubeCast, playing any video
- wait a couple of minutes

The video automatically restarts and resets back to 0. Also after stopping the playback from Kodi, after that happens, the video will start playing back again, later.

If there're multiple videos in the youtube playlist, after the restart, the first video starts at 0 instead of the currently selected one.

**Comment by pannal** [comment] 2018-05-16 22:04
Log files are in the linked issue.

**Comment by saunderez** [comment] 2018-05-19 03:47
Can confirm the same problem here. I blamed my phone at first (thought battery optimisation was essentially restarting YouTube) but the problem persisted after I turned battery optimisation off. Can provide logs if you want another sample.

**Comment by pannal** [comment] 2018-05-25 13:49
Any news here? Can you reproduce it @enen92 or do you need more information?

**Comment by enen92** [comment] 2018-05-25 14:40
I think the problem is that the "persistent" HTTP GET connection to youtube to listen to remote commands is closed by the server after a few time due to a series of noops while you are playing the file without issuing any operation (e.g. setVolume, seek, etc). This is the expected behaviour and what the addon does is to restart the connection. I think when this connection is restarted youtube send the last commands that were not noop: `auth`, `setPlaylist`, `getVolume` hence the addon restarts the video playback even though the video is still playing.
I think this is easily solved by keeping the state/video id at the player object and only issue the playback request if the setPlaylist command has a different videoid.
My time is limited at the moment and developing/debugging this addon is really time consuming

**Comment by pannal** [comment] 2018-05-25 14:59
Ah OK, that sounds about right. Thanks for investigating - take your time :)

**Comment by enen92** [comment] 2018-05-25 19:35
@pannal @saunderez @rcojr can you please test https://github.com/enen92/script.tubecast/commit/13eb13c5ac177feff2e6e4d636dde2237a4322ec before I submit to the repository? Just download and manually install by zip file.
It now tracks received codes and only executes those that have an higher value than the last one.

**Comment by pannal** [comment] 2018-05-26 03:10
Of course, will test it today.

**Comment by rcojr** [comment] 2018-05-26 04:29
@enen92 I just tested and it's now working great, thanks!

**Comment by und3rdg** [comment] 2018-05-26 11:06
When we can expect this update in kodi report?

**Comment by enen92** [comment] 2018-05-26 12:31
Submitted to repo: https://github.com/xbmc/repo-scripts/pull/853

**Closed by enen92** 2018-05-26 12:31 UTC
